import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="font-heading">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet" />
      </head>
      <body className="bg-ivory text-espresso font-body">
        {/* Top Navigation */}
        <nav className="sticky top-0 z-50 bg-ivory border-b border-sand h-16 flex items-center justify-between px-6 max-w-[1200px] mx-auto" role="navigation" aria-label="Main Navigation">
          <div className="flex items-center gap-4">
            <a href="/" className="flex items-center h-12 w-12 mr-4">
              <img src="/traditio_logo.png" alt="Traditio Logo" className="h-10 w-10 object-contain" />
            </a>
          </div>
          <ul className="flex-1 flex justify-center gap-8 text-sm font-bold tracking-wider uppercase font-body">
            <li><a href="/" className="hover:text-brass transition-colors duration-200">Home</a></li>
            <li><a href="/about" className="hover:text-brass transition-colors duration-200">About</a></li>
            <li><a href="/showroom" className="hover:text-brass transition-colors duration-200">Showroom</a></li>
            <li><a href="/blog" className="hover:text-brass transition-colors duration-200">Blog</a></li>
            <li><a href="/viewings" className="hover:text-brass transition-colors duration-200">Viewings</a></li>
            <li><a href="/delivery" className="hover:text-brass transition-colors duration-200">Delivery</a></li>
            <li><a href="/contact" className="hover:text-brass transition-colors duration-200">Contact</a></li>
          </ul>
          <div className="flex items-center gap-6">
            <a href="/account" className="hover:text-brass transition-colors duration-200">Sign In</a>
            <a href="/cart" className="relative hover:text-brass transition-colors duration-200">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6 inline">
                <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.836l.383 1.437m0 0l1.35 5.062c.13.487.576.83 1.087.83h8.27c.51 0 .957-.343 1.087-.83l1.35-5.062m-12.144 0h12.144m-12.144 0l-.383-1.437A1.125 1.125 0 0 1 5.636 3h12.728c.51 0 .955.343 1.087.836l.383 1.437m-2.25 13.5a1.125 1.125 0 1 1-2.25 0 1.125 1.125 0 0 1 2.25 0zm-9 0a1.125 1.125 0 1 1-2.25 0 1.125 1.125 0 0 1 2.25 0z" />
              </svg>
              <span className="absolute -top-2 -right-2 bg-brass text-white text-xs rounded-full px-1.5 py-0.5">0</span>
            </a>
          </div>
        </nav>
        {/* Main Content */}
        {children}
        {/* Footer */}
        <footer className="bg-ivory border-t border-sand mt-16 py-12 text-sm">
          <div className="max-w-[1200px] mx-auto px-6 grid grid-cols-1 md:grid-cols-3 gap-8">
            <div>
              <h3 className="font-heading text-lg mb-2 uppercase tracking-wider">Contact</h3>
              <p>Traditio Interiors<br/>123 High Street<br/>Edinburgh, Scotland EH1 1AA</p>
              <p className="mt-2">Phone: <a href="tel:+441312345678" className="hover:underline">+44 131 234 5678</a></p>
              <p>Email: <a href="mailto:info@traditio.com" className="hover:underline">info@traditio.com</a></p>
              <p className="mt-2">Hours: Mon–Sat 10am–6pm</p>
            </div>
            <div>
              <h3 className="font-heading text-lg mb-2 uppercase tracking-wider">Newsletter</h3>
              <form className="flex flex-col gap-2">
                <input type="email" placeholder="Your email" className="border border-sand rounded px-3 py-2" aria-label="Email address" />
                <button type="submit" className="bg-sand text-espresso font-bold rounded px-4 py-2 border-2 border-brass transition-colors duration-200 hover:bg-espresso hover:text-ivory">Subscribe</button>
                <span className="text-xs text-sand mt-1">We respect your privacy.</span>
              </form>
            </div>
            <div>
              <h3 className="font-heading text-lg mb-2 uppercase tracking-wider">Legal</h3>
              <ul className="flex flex-col gap-1">
                <li><a href="/delivery" className="hover:underline">Delivery</a></li>
                <li><a href="/contact" className="hover:underline">Contact</a></li>
                <li><a href="/returns" className="hover:underline">Returns</a></li>
                <li><a href="/privacy" className="hover:underline">Privacy</a></li>
                <li><a href="/reviews" className="hover:underline">Reviews</a></li>
              </ul>
              <p className="mt-4 text-xs text-sand">&copy; {new Date().getFullYear()} Traditio Interiors. All rights reserved.</p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
